name: Build Il2CppDumper Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.1

    - name: Restore NuGet packages
      run: msbuild /t:restore

    - name: Build Il2CppDumper
      run: msbuild Il2CppDumper/Il2CppDumper.csproj /restore /p:Configuration=Release /p:OutputType=Exe

    - name: Upload Il2CppDumper
      uses: actions/upload-artifact@v2
      with:
        name: Il2CppDumper-windows
        path: Il2CppDumper/bin/Release/net6.0